### ISSUE TITLE
Unable to log HTML elements

### ISSUE THREAD

**Issue by mahesh0919** [elmah/Elmah#426] opened 2017-11-24 10:22 UTC
I have an MVC4 site with a controller action that has [ValidateInput(false)] and
Exception filter as below, in the exception Message I have **HTML tags.** 

When an exception is thrown inside that action, elmah does not log the exception.
**Elmah throwing an exception about "a potentially dangerous request....."**

  public class CustomExceptionFilterAttribute: HandleErrorAttribute
    {
        public override void OnException(ExceptionContext filterContext)
        {
            ErrorSignal.FromCurrentContext().Raise(filterContext.Exception);
        }
    }

is there any workaround to log HTML elements in Elmah ?

**Comment by atifaziz** [comment] 2017-11-25 12:41
This is a duplicate of #217.

**Closed by atifaziz** 2017-11-25 12:41 UTC
Labels: duplicate
