### ISSUE TITLE
Late Binding for Dependecies

### ISSUE THREAD

**Issue by samaniehsan** [elmah/Elmah#397] opened 2015-11-06 19:16 UTC
I really like to see an ELMAH that invokes assembly dependencies with a late binding.
to be more specific I would love to see a framework like MEF utilized to decouple Elmah from MySQL,sqlite and sqlce.

[MEF](https://msdn.microsoft.com/en-us/library/dd460648(v=vs.110).aspx)

**Comment by atifaziz** [comment] 2016-03-09 18:42
Duplicate of #292

**Closed by atifaziz** 2016-03-09 18:42 UTC
Labels: duplicate
